### ISSUE TITLE
Upload Edge web note fails

### ISSUE THREAD

**Issue by shawnhwei** [webnium/yabumi-universal-app#4]
Trying to upload an MS Edge web note (full page screenshot) even with no annotation fails. That is, open page in MS Edge, click the web note button, then share button, select Yabumi, upload.

After a few second a "something went wrong" notification comes up and the error message is just "undefined".

It actually sort of worked the first time I used it, I got the error message but when opening yabumi the image was there. All subsequent attempts have failed however.

**Comment by kanreisa** [comment]
@meetshawn thanks feedback.
I want to know information of your environment.
ex. Windows 10 Pro 10586.420, Core i7-3770, 16.0 GB RAM

**Comment by shawnhwei** [comment]
Windows 10 Pro 10586.420, Core i7-6700HQ, 32 GB RAM

**Comment by kanreisa** [comment]
Can you tell me that reproducing URLs?

**Comment by shawnhwei** [comment]
It was the Droplet creation page on Digitalocean.
https://cloud.digitalocean.com/droplets/new?size=512mb&region=sgp1&distro=ubuntu

**Comment by shawnhwei** [comment]
It happens on every website for me anyways.
Is there an image size limit? I have a 4k display so a full page screenshot is quite heavy.

**Comment by kanreisa** [comment]
![](https://yabumi.cc/155b5c1a4f40f58ed911ea44.png)
↓
![](https://yabumi.cc/155b5c2b16ffd6bfc55b20e1.png)
↓
[uploaded link](https://yabumi.cc/155b5c22f233c0b26668f193.png)

**Comment by kanreisa** [comment]
Currently, Filesize limit is 100MB. and uploading time limit is 30 seconds.

**Comment by shawnhwei** [comment]
This is what I get. I did try drawing on it first, didn't make a difference.

![error1](https://cloud.githubusercontent.com/assets/7190278/16559802/0c8ef1a4-4222-11e6-8e69-07f10bfceeba.png)
![error](https://cloud.githubusercontent.com/assets/7190278/16559808/10732ea2-4222-11e6-9fe5-e9afbfe2dd5d.png)

**Comment by kanreisa** [comment]
Did you reboot Windows?

**Comment by shawnhwei** [comment]
Just rebooted, also tried reinstalling from Windows store, same result.

**Comment by kanreisa** [comment]
that issue is share action only. right?

![](https://yabumi.cc/155b5d302366f3ba78ee9aaf.png)
Is this works fine?

**Comment by shawnhwei** [comment]
Camera button doesn't work at all, upload gives an error but the image shows up?

![1](https://cloud.githubusercontent.com/assets/7190278/16560141/10e2569a-4224-11e6-9e4d-3366edcbfdc9.PNG)
![2](https://cloud.githubusercontent.com/assets/7190278/16560147/1dfbea08-4224-11e6-8b23-05cd4a539988.PNG)

**Comment by kanreisa** [comment]
hmm, It's really something went wrong.
other apps is?

**Comment by shawnhwei** [comment]
Not much, I just reinstalled a few days ago haha. Actually the camera randomly started working totally fine now, but upload still gives an error with a successful upload. I am running Sandboxie, but Edge and Windows store apps don't run in the Sandbox.

![3](https://cloud.githubusercontent.com/assets/7190278/16560390/ae7b43d4-4225-11e6-9658-6582ab882a4e.PNG)

**Comment by kanreisa** [comment]
**workaround**
If you want to take screenshot of web page,
you can use Chrome and [Yabumi for Chrome](https://chrome.google.com/webstore/detail/yabumi-for-chrome/pkipobhcddgffnenhohcafaaekfndmcf).

**Comment by shawnhwei** [comment]
Alright.

I think the Camera error is unrelated, that error code is just an output of the Windows 10 Camera app. I never opened it before and it seems to work fine now. 

Is there no debug information I can provide you?

**Comment by kanreisa** [comment]
a bug detected. I will provide update soon.

**Comment by kanreisa** [comment]
:tada: new version released. it will be available in few hours.
